/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/api': RouteRecordInfo<'/api', '/api', Record<never, never>, Record<never, never>>,
    '/kanji/[literal]': RouteRecordInfo<'/kanji/[literal]', '/kanji/:literal', { literal: ParamValue<true> }, { literal: ParamValue<false> }>,
    '/proper-noun/[term]': RouteRecordInfo<'/proper-noun/[term]', '/proper-noun/:term', { term: ParamValue<true> }, { term: ParamValue<false> }>,
    '/radical/[literal]': RouteRecordInfo<'/radical/[literal]', '/radical/:literal', { literal: ParamValue<true> }, { literal: ParamValue<false> }>,
    '/search': RouteRecordInfo<'/search', '/search', Record<never, never>, Record<never, never>>,
    '/vocabulary/[term]': RouteRecordInfo<'/vocabulary/[term]', '/vocabulary/:term', { term: ParamValue<true> }, { term: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/about.vue': {
      routes: '/about'
      views: never
    }
    'src/pages/api.vue': {
      routes: '/api'
      views: never
    }
    'src/pages/kanji/[literal].vue': {
      routes: '/kanji/[literal]'
      views: never
    }
    'src/pages/proper-noun/[term].vue': {
      routes: '/proper-noun/[term]'
      views: never
    }
    'src/pages/radical/[literal].vue': {
      routes: '/radical/[literal]'
      views: never
    }
    'src/pages/search.vue': {
      routes: '/search'
      views: never
    }
    'src/pages/vocabulary/[term].vue': {
      routes: '/vocabulary/[term]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
